# Generated by Django 5.2.4 on 2025-07-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='audio_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
